#I made this for testing my knowledge
sudo: required
services:
 - docker
#before install test our project
before_install:
 - docker build -f ./client/Dockerfile.dev -t myproject:latest ./client
#run test script
script:
 - docker run -it myproject:latest npm test -- --coverage
# make docker images
after_success:
 - docker build -t 7015214645/test-client ./client
 - docker build -t 7015214645/test-server ./server
 - docker build -t 7015214645/test-nginx ./nginx
 - docker build -t 7015214645/test-worker ./worker
# docker login
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push docker images to docker hub
 - docker push 7015214645/test-client
 - docker push 7015214645/test-server
 - docker push 7015214645/test-nginx
 - docker push 7015214645/test-worker 
#how to deploy on beanstalk
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: TestDocker
  env: Testdocker-env
  bucket_name: elasticbeanstalk-us-east-2-863659641122
  bucket_path: testingDocker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
