sudo: required
services:
 - docker
#before install test our project
before_install:
 - docker build -f ./client/Dockerfile.dev -t myproject:latest ./client
#run test script
script:
 - docker run -it myproject:latest npm test -- --coverage
# make docker images
after_success:
 - docker build -t 7015214645/testClient ./client
 - docker build -t 7015214645/testServer ./server
 - docker build -t 7015214645/testNginx ./nginx
 - docker build -t 7015214645/testWorker ./worker
# docker login
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push docker images to docker hub
 - docker push 7015214645/testClient
 - docker push 7015214645/testServer
 - docker push 7015214645/testNginx
 - docker push 7015214645/testWorker 
